use_frameworks!

platform :ios, '9.0'

target 'IAPWaveProgressView_Example' do
  pod 'IAPWaveProgressView', :path => '../'

  target 'IAPWaveProgressView_Tests' do
    inherit! :search_paths

     pod 'Quick'
     pod 'Nimble'
     pod 'FBSnapshotTestCase'
     pod 'Nimble-Snapshots'
  end
end
